### ISSUE TITLE
Introduce a newtype for headers map used in EntryPoint and ToHeaders

### ISSUE THREAD

**Issue by catostrophe** [janstenpickle/trace4cats#124]
I would like to have a newtype wrapping `Map[String, String]` for headers being passed to `EntryPoint`'s and `ToHeaders`'s methods as [it's done in Natchez](https://github.com/tpolecat/natchez/blob/master/modules/core/shared/src/main/scala/Kernel.scala).

Something simple like the following would be fine:
```scala
final case class TraceHeaders(toMap: Map[String, String]) extends AnyVal
```

I would do it myself, if you're ok with the naming. Which module should it be put into. I suppose `core`?

The motivation is that in my codebase I write custom span injectors and I require optics for abstract type parameters, which parameterize endpoint inputs or evaluation context, and for optics, especially implicit ones, it is highly desirable to have newtypes. That is `Getter[Ctx, TraceHeaders]` is better than `Getter[Ctx, Map[String, String]]`.

I use it in my code, but I think it also may be useful in the library.

**Comment by janstenpickle** [comment]
@catostrophe that sounds good to me, I originally refrained as I didn't have much of a use case for it, but your's is a really good one. If you're OK do it, I'd happily accept a PR, but would you mind putting it in the `model` module please?

Thanks!

**Comment by catostrophe** [comment]
Ok. Will do!
