### ISSUE TITLE
Sttp integration module needs reorganization

### ISSUE THREAD

**Issue by catostrophe** [janstenpickle/trace4cats#128]
I suggest some changes:

- [x] rename `backend` package to `client` as it's named in `sttp`
- [x] consider support for `sttp.client3`
- [x] add integration with `tapir`: `ServerEndpoint` may be span injected (in many cases it is preferable over routes tracing)
- [x] add `common` package for common code used for sttp client and tapir integrations

**Comment by janstenpickle** [comment]
Nice, this all sounds good!

**Comment by catostrophe** [comment]
I suggest postpone it until more stable versions of tapir and sttp are released. The main API has changed recently (capabilities added) and it affects the way we transform effects.

**Comment by catostrophe** [comment]
I started working on client3/tapir support.
