### ISSUE TITLE
Wrong SpanRefType mapping in JaegerSpanExporter

### ISSUE THREAD

**Issue by catostrophe** [janstenpickle/trace4cats#151]
I think there is an error in the mapping between the internal `trace4cats` span model and the Jaeger model.

https://github.com/janstenpickle/trace4cats/blob/82baa78bd7ee1c5e7742d99d4f53477a43bd76f7/modules/jaeger-thrift-exporter/src/main/scala/io/janstenpickle/trace4cats/jaeger/JaegerSpanExporter.scala#L76-L77

Here's the link to an interesting discussion regarding their meaning:
https://github.com/open-telemetry/opentelemetry-specification/issues/65

They both mean "parent" or "ancestor", not a child, but in a bit different way.

The below quote is especially interesting:
> Another odd thing about child-of and follows-from is that it's the child span that defines this reference type, even though it talks about parent's dependency on child outcome. If you're a remote server, how do you even know if parent/caller does or does not depend on your outcome? I tend to think of this as the nature of the protocol: producer of a message to Kafka does not respect any response, so the receiver should use follows-from. Sender of HTTP request does expect a response, so the server always uses child-of, even of the sender doesn't care about the outcome - in that case it can internally create a follows-from span first, and then a normal pair of RPC call spans. So it's possible to rationalize this way, but it's still kind of dirty.  

I suggest changing it to:
```scala
case Link.Parent(_, _) => new SpanRef(SpanRefType.CHILD_OF, traceIdLow, traceIdHigh, spanId) 
```
That is when we add a link `Parent(parentTraceId, parentSpanId)` we mean that the current span is a **child of** (parentTraceId, parentSpanId).

**Comment by janstenpickle** [comment]
Yes, this is confusing, and seems to be open to lots of interpretation. I think it may be better to remove `Link.Child` for the time being and do the same as open-telemetry

**Comment by catostrophe** [comment]
For some reason, `CHILD_OF` is used as a ref type in the json response of `http://localhost:16686/api/traces/` for links to the direct parents in the same trace.
I suggest mapping Link.Parent to `FOLLOWS_FROM` and use it for linking with indirect/async parents.

**Comment by janstenpickle** [comment]
> I suggest mapping Link.Parent to `FOLLOWS_FROM` and use it for linking with indirect/async parents.

This is what currently happens for that link type in order to align with the OT implementation. The only difference is the already problematic `Link.Child`, so I think that should just be removed completely.

**Comment by catostrophe** [comment]
But child links are used in the stackdriver exporter.

**Comment by janstenpickle** [comment]
They are, but as you point out, the Jaeger data model doesn't allow for specifying children on the parent span. So while Stackdriver does support this other systems will either behave in weird ways or drop the link completely.

That said, there isn't a way to have multi-parent spans in datadog or newrelic at all. I'm just not conviced of the utility of being able to specify child spans in the parent span post-hoc, especially as the ability to specify one or more parent is available for a child anyway.

**Comment by catostrophe** [comment]
I can do this one.

Do you prefer to leave just `case class Link(...)` or `sealed trait Link` with only one case `Parent`?

Or we still have another option: find all folds on `Link` and turn them into partial functions, so that if a case is not supported by a tracing backend, we ignore it.

**Comment by janstenpickle** [comment]
Thanks @catostrophe.I'm struggling to think of a use case for a child link given the open telemetry discussion. While stackdriver supports the concept of a child link, is it something we _should_ support in the API? I'm leaning towards not, given that modifying a parent to add a child link could get complicated. What do you think? 

If you think the same, we should probably just go with a single case class `Link`.

**Comment by catostrophe** [comment]
I agree, let's make it `case class Link(...)`. Will do.
