### ISSUE TITLE
The need for no-op entities

### ISSUE THREAD

**Issue by catostrophe** [janstenpickle/trace4cats#17]
In order to make tracing optional (switchable) at the application level, e.g. via config, we need to be able to create no-op instances of some entities.

We have one for `Trace`. But the one for `EntryPoint` is missing. As to implement it, we need a `NoopSpan` which in turn cannot be created without the empty `SpanContext`.

I will add those listed above if we define what the empty SpanContext is.

**Comment by catostrophe** [comment]
I suggest this:
```
{
  traceId = Array.fill(16)(0),
  spanId = Array.fill(8)(0),
  parent = None,
  traceFlags = false,
  traceState = empty,
  isRemote = false
}
```

**Comment by catostrophe** [comment]
Wow. I just noticed you've already added NoopSpan directly to the master. If you did it via a PR I would notice it before I opened this issue.

Anyway I am going to add NoopEntryPoint

**Comment by janstenpickle** [comment]
> Wow. I just noticed you've already added NoopSpan directly to the master. If you had done it via a PR, I would have noticed it before I opened this issue.

No problem and thanks! Sorry I'm still being a bit bad with my commits, I'll do PRs in the future so changes are a bit more visible.

Looks like we're on the same page with some of these changes!
