### ISSUE TITLE
AvroSpanExporter shouldn't check the queue for elements on release

### ISSUE THREAD

**Issue by catostrophe** [janstenpickle/trace4cats#340]
TODO:
1. Rely on the semaphore only.
2. Fix the check for acquired permits.
3. Add an optional parameter for the number of worker fibers (under discussion).

**Comment by catostrophe** [comment]
I will take this one but we need to agree on the fiber number/queue capacity. Shall I make it a parameter? Will it make any sense?

**Comment by janstenpickle** [comment]
Thanks. Yeah I think make it parameter with a default, we can tune it later on then
