### ISSUE TITLE
Remove unnecessary usages of blocker

### ISSUE THREAD

**Issue by janstenpickle** [janstenpickle/trace4cats#343]
As raised in #324 `Blocker` usage is not necessary for http clients.

**Comment by catostrophe** [comment]
TODO:
1. replace passing `Blocker`s with passing a dedicated EC (this is still mandatory on CE2)
2. make stackdriver grpc integration async
3. keep `Blocker` only for Jaeger thrift udp sender

**Comment by catostrophe** [comment]
stackdriver grpc integration may be copied from the CE3 branch, except for one thing:
Instead of using `Async[F].executionContext` this one should be used:
`com.google.common.util.concurrent.MoreExecutors.directExecutor()`
