### ISSUE TITLE
Drop better-monadic-for plugin

### ISSUE THREAD

**Issue by catostrophe** [janstenpickle/trace4cats#352]
This is a blocker for migration to Scala 3. Not an urgent thing but something we definitely should do sooner or later. Currently, it's used mostly for passing implicit loggers and such pieces of code can be easily rewritten without bm4.

**Comment by janstenpickle** [comment]
Discussed in #534, we will leave this in for Scala 2 builds indefinitely, but avoid using features not supported by Scala 3. Crossbuilds should prevent unsupported code being added in the future.
