### ISSUE TITLE
ClientSyntax/RoutesSyntax: issues with inject

### ISSUE THREAD

**Issue by IndiscriminateCoding** [janstenpickle/trace4cats#43]
There is some issues with `inject` implementation for both client and server:

- `Span#setStatus` isn't called on error or cancel - probably, bracket-like method should be used instead of `flatMap`?
- `RoutesSyntax#inject` operates on `HttpRoutes`, ignoring "not found"/`None` case - one option would be to translate `HttpApp`, which already have this case converted to 404;
- Client inject uses `Client#toHttpApp` - that would cause connection leak in some setups if HTTP body isn't consumed (for example, if a client don't read it on 4xx errors).

Please correct me if my view is incomplete or if I'm missing something here.

**Comment by janstenpickle** [comment]
Thanks for raising @IndiscriminateCoding and sorry I haven't addressed this more quickly, I've been on holiday.

> Span#setStatus isn't called on error or cancel - probably, bracket-like method should be used instead of flatMap?

I didn't realise this was the case, I haven't looked at it yet, but you're almost certainly right

> RoutesSyntax#inject operates on HttpRoutes, ignoring "not found"/None case - one option would be to translate HttpApp, which already have this case converted to 404

This was a relatively deliberate decision, but like you say `HttpApp` would work here too.

> Client inject uses Client#toHttpApp - that would cause connection leak in some setups if HTTP body isn't consumed (for example, if a client don't read it on 4xx errors).

I didn't realise this either, I've been using something similar with Natchez in the past and didn't realise this was an issue. I think this should be better supported if I use this: https://github.com/http4s/http4s/pull/3552

**Comment by janstenpickle** [comment]
@IndiscriminateCoding do you have some example code of where `Span#setStatus` isn't called? The root span is always consumed with `use`, which _should_ set the status on error or cancel (see the tests here https://github.com/janstenpickle/trace4cats/blob/master/modules/core/src/test/scala/io/janstenpickle/trace4cats/SpanSpec.scala).

**Comment by IndiscriminateCoding** [comment]
@janstenpickle I think you are right that span status is eventually set.

However, it is unclear where span boundaries are: looking at `ClientSyntax#inject` types, I'd expect it to create a child span using `spanNamer` for each request.

But if I understand correctly, [it doesn't](https://github.com/janstenpickle/trace4cats/blob/37763d523d4644e5186fdbf18b19ef2eb4b01adb/modules/http4s-client/src/main/scala/io/janstenpickle/trace4cats/http4s/client/ClientSyntax.scala#L28) because created child only used to `mapK` over supplied requests (so it only used while reading from a request body, which is quite unlikely to use any of tracing functionality at all).

Actual request on an underlying `Client` still uses the same span that is used to make original request.

While it's possible that user don't want to set a new span for all requests automatically, I think status quo would result in a weird corner cases (for example, if she makes more than one request subsequently, status from the last one wins - while others are silently ignored).

Probably it would be useful to analyze lifetimes of a `Span` w.r.t. `setStatus` - either it should be set in a client on any outcome (success/failure/cancel), or shouldn't be set at all, making it possible for a user to precisely control lifetimes of a span.

**Comment by janstenpickle** [comment]
Hey @IndiscriminateCoding thanks for the extra detail and sorry again for the delay - I've been working on something which should fix the issue with the client, but got sidetracked with something else. I've got something that works well based on https://github.com/http4s/http4s/pull/3552, but I'm currently in the process of adding tests to make sure the status is set on the correct span.

**Comment by janstenpickle** [comment]
@IndiscriminateCoding This should be fixed as of #49, pending a `0.4.0` release version `0.3.0+71-4ec5fa86` will have fix included.
