### ISSUE TITLE
Case sensitivity in b3 headers

### ISSUE THREAD

**Issue by soujiro32167** [janstenpickle/trace4cats#467]
I am trying to see a call flow from Envoy to a backend that uses trace4cats. The incoming headers include b3 headers, like this:

![image](https://user-images.githubusercontent.com/6598104/117339547-dac5da80-ae6d-11eb-8416-80970a46f02d.png)

However, in Jaeger UI, I cannot see the connection between the parent trace from Envoy and the child created by trace4cats.
It looks like [here](https://github.com/janstenpickle/trace4cats/blob/master/modules/core/src/main/scala/io/janstenpickle/trace4cats/B3ToHeaders.scala) the headers are compared directly, with case sensitivity, whereas the protocol allows lower case headers:

https://github.com/openzipkin/b3-propagation

**Comment by catostrophe** [comment]
Closed via #468
