### ISSUE TITLE
Inverted meaning for `Traceflags#sampled`

### ISSUE THREAD

**Issue by xicmiah** [janstenpickle/trace4cats#53]
Looks like project uses inverted value for the `sampled` flag.

In [W3C Trace Context](https://www.w3.org/TR/trace-context-1/#sampled-flag) `true`/`01` means "the caller may have recorded trace data", but in `SpanSampler#shouldSample`/`Span` `true` means "don't report the span". The latter is consistent across the project, except for `ToHeaders.w3c`, which passes the flag as-is.

I may be misunderstanding flag semantics, but wouldn't that effectively disable child traces?

**Comment by janstenpickle** [comment]
You're right @xicmiah, nice spot, thank you. I'll push a fix shortly
