### ISSUE TITLE
[opentelemetry-common] ManagedChannel gets shut down via exporter

### ISSUE THREAD

**Issue by catostrophe** [janstenpickle/trace4cats#62]
`Exporter` gets created and closed for each batch. But `exporter.shutdown()` causes `channel.shutdown()`.

https://github.com/janstenpickle/trace4cats/blob/5f71eeeaca7fb88391e8cb326ae3ac3540cd871f/modules/opentelemetry-common/src/main/scala/io/janstenpickle/trace4cats/opentelemetry/common/OpenTelemetryGrpcSpanExporter.scala#L44-L47

**Comment by janstenpickle** [comment]
Oh damn, nice catch @catostrophe
